<!-- header commun a toutes les pages -->




<div class="background1">
    <?php include("Layout-header.phtml"); ?>
<div class="titre"><h1>Billet simple pour<br>l'Alaska</h1></div>
</div>


<div class="background">
    <div class="container">
        <div class="row">
        <aside class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="billets">
            <h2 id="Billets">Billets</h2>
            </div>

            <div class="color">

            <p class="border"><?php foreach ($articles

                as $article) : ?>

            <p class="text1"><?php echo $article['title']; ?></p>

            <p ><?php echo html_entity_decode($article['content']); ?></p>
            <p><?php echo $article['author']; ?> <br>

                Poster le : <?php echo $article['date_article']; ?></p>

            <a href="detail?article=<?= $article['id']; ?>">detail de l'article</a>
            <?php endforeach; ?>

            </p>
            </div>
        </aside>
        </div>
    </div>



<!-- footer commun a toutes les pages -->

<?php include("Layout-footer.phtml"); ?>
</div>


</body>

