<!-- header commun a toutes les pages -->

<?php include("Layout-header.phtml"); ?>
<div class="titre">
    <h1>Billet simple pour<br>l'Alaska</h1>
</div>


<div class="container">
    <aside class="col-lg-12">
        <div class="billets">
            <h2 id="Billets">Billets</h2>
        </div>

        <div class="color">

            <p class="border"><?php foreach ($articles

                as $article) : ?>

            <p class="text1"><?php echo $article['title']; ?></p>

            <p class="text"><?php echo $article['content']; ?></p>

            <p class="text"><?php echo $article['author']; ?></p>

            <p class="text">Posted by Auteur : <?php echo $article['date_article']; ?></p>

            <a class="text" href="detail?article=<?= $article['id']; ?>">detail de l'article</a>
            <<?php endforeach; ?>

            </p>

        </div>
    </aside>

</div>



<!-- footer commun a toutes les pages -->

<?php include("Layout-footer.phtml"); ?>


</body>

