<?php
if(!isset($_SESSION)){
    session_start();
} ?>

<?php include("Layout-header.phtml"); ?>


<div class="titre">
    <h1> Administration des articles</h1>
</div>


<div class="container">

    <table class="table-bordered">
        <tr>
            <td>
                <p><?php foreach ($articles

                    as $article) ?>

                <p><?php echo $article['title']; ?></p>

                <p><?php echo $article['content']; ?></p>

                <p><?php echo $article['author']; ?></p>

                <p>Posted by Auteur : <?php echo $article['date_article']; ?></p>
            </td>
            <td>
                <div class="btn-group-vertical">
                    <a href="/app/view/article-creation.php"><button type="button" class="btn btn-primary">Creation Article</button></a>
                    <a href="/app/view/article-modification.php"><button type="button" class="btn btn-success">Modifier Article</button></a>
                    <button type="button" class="btn btn-danger">Suprimer</button>
                </div>
            </td>
        </tr>
    </table>
</div>




<?php include("Layout-footer.phtml"); ?>

