<?php
if (!isset($_SESSION)) {
    session_start();
} ?>

<?php include("Layout-header.phtml"); ?>


<div class="titre">
    <h1> Administration des articles</h1>
</div>

<?php
if (!empty($_SESSION['msg'])) {
    echo '<h3 style="background:blue;color:white;">' . $_SESSION['msg'] . '</h3>';
    unset($_SESSION['msg']);
}
?>


<div class="container">
    <table class="table table-bordered">
        <a href="save_article"><button type="button" class="btn btn-primary btn-lg btn-block">Créer un nouvelle article</button></a><br/>
        <thead>
        
        <tr>
            <th class="text-center">Titre</th>
            <th class="text-center">Billets</th>
            <th class="text-center">Action</th>
        </tr>
        </thead>


            <?php foreach ($articles as $article): ?>


        <tr>
            <td>
                <p class="text"><?php echo $article['title']; ?></p>
            </td>

            <td>
                <p><?php echo html_entity_decode($article['content']); ?></p>
                <p><?php echo $article['author']; ?></p>
                <p>Posted by Auteur : <?php echo $article['date_article']; ?></p>
            </td>

            <td class="text-center">
                <a href="modification?article=<?= $article['id']; ?>" class="btn btn-success btn-lg"><span class="glyphicon glyphicon-edit"></span>Modifier</a>

                <a href="delete_Billet?article=<?= $article['id']; ?>" name="id" class="btn btn-danger btn-lg"><span class="glyphicon glyphicon-remove"></span>Suprimer</a>
            </td>

        </tr>
            <?php endforeach; ?>

    </table>

</div>





<?php include("Layout-footer.phtml"); ?>

