<?php
if (!isset($_SESSION)) {
    session_start();

} ?>



    <div class="background2">
    <?php include("Layout-header.phtml"); ?>
    <h1> Administration des articles</h1>


    <div class="container">

    <div class="msg">
        <?php
        if (!empty($_SESSION['msg'])) {

           echo '<h3>' .$_SESSION['msg']. '</h3>';
            unset($_SESSION['msg']);
        }
        ?>
    </div>

    <td class="text-center text2">
                    <a href="only_article?article=" class="btn btn-info btn-lg btn3d"><span
                                class="glyphicon glyphicon-ok"></span>Articles</a>

                    <a href="only_comment?article=" name="id"
                       class="btn btn-info btn-lg btn3d"><span class="glyphicon glyphicon-ok"></span>Commentaires</a>

                    <a href="save_article?article=" name="id"
                       class="btn btn-success btn-lg btn3d"><span class="glyphicon glyphicon-ok"></span>Créer un nouvelle article</a>
    </td>

        <table class="table table-bordered">

         <thead>
            <tr>
                <th class="text-center">Titre</th>
                <th class="text-center">Billet</th>
                <th class="text-center">Action</th>
            </tr>
        </thead>


            <?php foreach ($articles
            as $article): ?>

            <tr>
                <td class="background4">
                    <p class="text"><?php echo $article['title']; ?></p>
                </td>

                <td class="text2">
                    <p><?php echo html_entity_decode($article['content']); ?></p>
                    <p><?php echo $article['author']; ?></p>
                    <p>Posted by Auteur : <?php
                $datef =  DateTime::createFromFormat('Y-m-d H:i:s', $article['date_article']);
                echo $datef->format('d-m-Y');
                ?></p>

                </td>

                <td class="text-center text2">
                    <a href="modification?article=<?= $article['id']; ?>" class="btn btn-success btn-lg btn3d"><span
                                class="glyphicon glyphicon-ok"></span>Modifier</a>

                    <a href="delete_Billet?article=<?= $article['id']; ?>" name="id"
                       class="btn btn-danger btn-lg btn3d"><span class="glyphicon glyphicon-ok"></span>Suprimer</a>
                </td>
    </div>
    </tr>
    <?php endforeach; ?>
    </table>



</div>



<?php include("Layout-footer.phtml"); ?>

