<!-- header commun a toutes les pages -->




<div class="background2">
    <?php include("Layout-header.phtml"); ?>
<div class="container">


    <h1 class="titreDetail">Billet de Jean</h1>
<div class="titre-article">
    <p>
        <?php echo $article['title']; ?>
    </p>

        <?php echo html_entity_decode($article['content']); ?>

    <p class="authorDetail">
        <?php echo $article['author']; ?><br>

        <?php echo 'paru le : ' .  $article['date_article']; ?>
    </p>

</div>

</div>
</div>
<!-- footer commun a toutes les pages -->

    <?php include("Layout-footer.phtml"); ?>



