<?php
require_once(dirname(__FILE__) . "/../Controller/Controller.php"); ?>


<div class="background2">
    <?php include("Layout-header.phtml"); ?>


    <h1 id="timeline">Billet de Jean</h1>
    <div class="container">
        <p>
            <h3><?php echo $article['title']; ?></h3>
        </p>
        <h4><?php echo html_entity_decode($article['content']); ?></h4>

        <p class="authorDetail">
            <?php echo $article['author']; ?><br>

            <?php echo 'paru le : ' . $article['date_article']; ?>
        </p>

    </div>


    <div>
        <div class="container" style="padding-top:30px">


            <div class="row">
                <div class="span-3 well" style="padding-bottom:0">

                    <form class="contour" action="save_comment" method="post">
                        <label for="content"><h1>Laisser un commentaire</h1></label>
                        <label for="pseudo"></label><br>
                        <input class="form-control" type="text" name="pseudo" id="pseudo" placeholder="pseudo"/>
                        <br>
                        <textarea class="span4" id="content" name="content" placeholder="Laisser un commentaire"
                                  rows="6"></textarea>
                        <input type="hidden" name="id_article" id="id_article"
                               value="<?php echo @(int)$_GET['article']; ?>"/>
                        <h6 class="pull-right">320 characters remaining</h6>
                        <button class="btn btn-primary btn-lg btn3d" type="submit"><span
                                    class="glyphicon glyphicon-ok"></span>Poster</a></button>
                    </form>

                </div>
            </div>

            <h1 class="text-center">Vos Commentaires</h1>

            <table class="table table-bordered tableau">

                <thead>
                <tr>
                    <th class="text-center">Pseudo</th>
                    <th class="text-center">Commentaire</th>
                </tr>
                </thead>


                    <?php foreach ($comments as $comment): ?>

                    <tr>
                        <td class="background4">
                            <p class="text"><?php echo $comment['pseudo'] ?></p>
                        </td>

                        <td class="text">
                            <p><?php echo ($comment['content']); ?></p>
                            <p class="bouton2">Posted : <?php echo $comment['comment_date'] ?></p>
                            <form class="bouton1">
                                <INPUT type="checkbox" name="choix1" value="1"> Signaler ce commentaire
                            </form>
                        </td>

                    </tr>
                <?php endforeach; ?>

            </table>
        </div>
    </div>


    <div>
        <div class="row">
            <div class="col-lg-12">
                <?php include("Layout-footer.phtml"); ?>
            </div>
        </div>
    </div>