

<head>
    <meta charset="utf-8"/>
    <link href="../../bootstrap/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../../css/style.css"/>
    <link rel="stylesheet" type="text/css" href="../../css/admin.css"/>
    <link rel="stylesheet" type="text/css" href="../../css/detail.css"/>
    <style type="text/css"></style>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
    <script>tinymce.init({selector: 'textarea'});</script>
    <link rel="icon" type="image/png" href="../../img/livre.png"/>
    <title>Blog Jean Forteroche</title>
</head>