<!--  header  -->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <link rel="stylesheet" type="text/css" href="/css/admin.css"/>
    <link rel="stylesheet" type="text/css" href="/css/detail.css"/>
    <style type="text/css"></style>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>




    <link rel="icon" type="image/png" href="/img/livre.png"/>

    <title>Blog Jean Forteroche</title>
</head>

<body>


<header>

        <nav>
            <ul class="menu">
                <li><a class="ancre" href="/index.php/">Accueil</a></li>
                <li><a class="ancre" href="/index.php/#Billets">Billets</a><br/></li>
                <li><a class="connect" href="/app/view/connect.phtml">Se connecter<?php if(!isset($_SESSION)){
                    echo 'se deconnecter';
                } ?> </a></li>
            </ul>
        </nav>

</header>

</body>
</html>








