<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <style type="text/css">

        [class*="container"] {
            height: 1420px;
        }

    </style>
    <link rel="icon" type="image/png" href="/img/livre.png"/>

    <title>Blog Jean Forteroche</title>
</head>
<body>


<header class="background1">

    <div class="container container-fluid">
        <?php include("header.phtml"); ?>
    </div>

</header>

<div class="container">
    <aside class="col-lg-12">
        <div class="billets">
            <h2 id="Billets">Billets</h2>
        </div>

        <div class="color">

            <p class="border"><?php foreach ($articles

                as $article) : ?>

            <p class="text1"><?php echo $article['title']; ?></p>

            <p class="text"><?php echo $article['content']; ?></p>

            <p class="text"><?php echo $article['author']; ?></p>

            <p class="text">Posted by Auteur : <?php echo $article['date_article']; ?></p>

            <a class="text" href="detail?article=<?= $article['id']; ?>">detail de l'article</a>
            <hr>
            <?php endforeach; ?>


            <ul class="pagination">

                <li><a href="#">&laquo;</a></li>

                <li><a href="#">1</a></li>

                <li><a href="#">2</a></li>

                <li><a href="#">3</a></li>

                <li><a href="#">&raquo;</a></li>

            </ul>


            </p>

        </div>
    </aside>

</div>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<!-- footer commun a toutes les pages -->

<?php include("footer.phtml"); ?>


</body>
</html>
