<!-- header commun a toutes les pages -->

<?php include("header.phtml"); ?>

<div class="container">
    <aside class="col-lg-12">
        <div class="billets">
            <h2 id="Billets">Billets</h2>
        </div>

        <div class="color">

            <p class="border"><?php foreach ($articles

                as $article) : ?>

            <p class="text1"><?php echo $article['title']; ?></p>

            <p class="text"><?php echo $article['content']; ?></p>

            <p class="text"><?php echo $article['author']; ?></p>

            <p class="text">Posted by Auteur : <?php echo $article['date_article']; ?></p>

            <a class="text" href="detail?article=<?= $article['id']; ?>">detail de l'article</a>
            <<?php endforeach; ?>


            <ul class="pagination">

                <li><a href="#">&laquo;</a></li>

                <li><a href="#">1</a></li>

                <li><a href="#">2</a></li>

                <li><a href="#">3</a></li>

                <li><a href="#">&raquo;</a></li>

            </ul>
            <div id="demo"></div>

            </p>

        </div>
    </aside>

</div>


<script> $('#demo').pagination({
        dataSource: [1, 2, 3, 4, 5, 6, 7,..., 195
    ],
    callback: function (data, pagination) {
        // template method of yourself
        var html = template(data);
        dataContainer.html(html);
    }
    })</script>


<!-- footer commun a toutes les pages -->

<?php include("footer.phtml"); ?>


</body>

