<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <link rel="icon" type="image/png" href="/img/livre.png"/>
    <title>Article de Jean Forteroche </title>
</head>
<body>
<header class="background">
    <nav>
        <ul class="menu">
            <li><a class="ancre" href="/index.php/">Accueil</a></li>
            <li><a class="ancre" href="/index.php/#Billets">Billets</a></li>
        </ul>
    </nav>
    <h1 class="titreDetail">Billet de Jean</h1>

    <p class="textDetail">
        <br>
        <?php echo $article['title']; ?>
        <br/>
        <?php echo $article['content']; ?>
        <br/>
        <?php echo $article['author']; ?>
    </p>
</header>


<footer>
    <?php include("footer.phtml"); ?>
</footer>

</body>
</html>