

            <!-- le header commun a toutes les page Admin -->
<nav>
    <ul class="menu">
        <li><a class="ancre" href="/index.php/">Accueil</a></li>

    </ul>
    <ul>
        <li><a class="connect" href="/app/Vue/connect.phtml">Se Deconnecter</a></li>
    </ul>

</nav>


<div id="logo">
    <a href="https://www.facebook.com" target="_blank"><img src="/img/facebook.png" alt="logo"/></a>
    <a href="https://accounts.google.com" target="_blank"><img src="/img/twitter.png" alt="logo"/></a>
    <a href="https://twitter.com/?lang=fr" target="_blank"><img src="/img/googleplus.png" alt="logo"/></a>
</div>
