

       <!--  header specifique a la page d'accueil visiteur -->


       <div class="row">
           <div class="col-lg-12">

<nav>
    <ul class="menu">
        <li><a class="ancre" href="/index.php/">Accueil</a></li>
        <li><a class="ancre" href="#Billets">billets</a><br/></li>
        <li><a class="connect" href="/app/Vue/connect.phtml">Se Connecter</a></li>
    </ul>
           </div>
       </div>

</nav>


<div class="titre">
    <h1>Billet simple pour<br>l'Alaska</h1>
</div>
<div id="logo">
    <a href="https://www.facebook.com" target="_blank"><img src="/img/facebook.png" alt="logo"/></a>
    <a href="https://accounts.google.com" target="_blank"><img src="/img/twitter.png" alt="logo"/></a>
    <a href="https://twitter.com/?lang=fr" target="_blank"><img src="/img/googleplus.png" alt="logo"/></a>
</div>
